// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1gXoKT8sqk3HDWamVR3qjXoGoSsOHwmU',
    appId: '1:2189201155:android:d6f60ea64705baf1256336',
    messagingSenderId: '2189201155',
    projectId: 'house-backend',
    databaseURL: 'https://house-backend-default-rtdb.firebaseio.com',
    storageBucket: 'house-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugQk_tCBOYFuWh7AEfo6PAWwGkEuWWTU',
    appId: '1:2189201155:ios:3752abe7be693b48256336',
    messagingSenderId: '2189201155',
    projectId: 'house-backend',
    databaseURL: 'https://house-backend-default-rtdb.firebaseio.com',
    storageBucket: 'house-backend.appspot.com',
    iosClientId: '2189201155-l8j4jlnidj708ea50jiqej5idfqvh5i2.apps.googleusercontent.com',
    iosBundleId: 'com.house.app',
  );
}
