import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';
import '../models/house_note.dart';
import '../providers/house_notes_provider.dart';
import '../../../core/providers/houses_provider.dart';
import '../../../core/providers/auth_provider.dart';

class AddEditNoteDialog extends ConsumerStatefulWidget {
  final HouseNote? note; // If null, it's add mode

  const AddEditNoteDialog({super.key, this.note});

  @override
  ConsumerState<AddEditNoteDialog> createState() => _AddEditNoteDialogState();
}

class _AddEditNoteDialogState extends ConsumerState<AddEditNoteDialog> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _titleController;
  late TextEditingController _contentController;
  late NoteUrgency _urgency;
  late bool _isPinned;

  @override
  void initState() {
    super.initState();
    _titleController = TextEditingController(text: widget.note?.title ?? '');
    _contentController = TextEditingController(
      text: widget.note?.content ?? '',
    );
    _urgency = widget.note?.urgency ?? NoteUrgency.info;
    _isPinned = widget.note?.isPinned ?? false;
  }

  @override
  void dispose() {
    _titleController.dispose();
    _contentController.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (_formKey.currentState!.validate()) {
      final houseId = ref.read(currentHouseIdProvider);
      final user = ref.read(authStateProvider).value;

      if (houseId == null || user == null) return;

      if (widget.note == null) {
        // Add
        final newNote = HouseNote(
          id: '', // Generated by repo/firestore
          houseId: houseId,
          creatorId: user.uid,
          title: _titleController.text.trim(),
          content: _contentController.text.trim(),
          urgency: _urgency,
          isPinned: _isPinned,
          createdAt: DateTime.now(),
        );
        await ref.read(houseNotesControllerProvider.notifier).addNote(newNote);
      } else {
        // Update
        final updatedNote = widget.note!.copyWith(
          title: _titleController.text.trim(),
          content: _contentController.text.trim(),
          urgency: _urgency,
          isPinned: _isPinned,
        );
        await ref
            .read(houseNotesControllerProvider.notifier)
            .updateNote(updatedNote);
      }

      if (mounted) {
        Navigator.of(context).pop();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.note != null;

    return Dialog(
      backgroundColor: AppColors.cardDark,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.all(20.0),
        child: SingleChildScrollView(
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  isEditing ? 'Edit Note' : 'New Note',
                  style: AppTextStyles.cardTitle,
                ),
                const SizedBox(height: 20),

                // Title
                TextFormField(
                  controller: _titleController,
                  style: AppTextStyles.body,
                  decoration: InputDecoration(
                    labelText: 'Title',
                    labelStyle: AppTextStyles.bodySecondary,
                    enabledBorder: const UnderlineInputBorder(
                      borderSide: BorderSide(color: AppColors.textSecondary),
                    ),
                    focusedBorder: const UnderlineInputBorder(
                      borderSide: BorderSide(color: AppColors.primaryPurple),
                    ),
                  ),
                  validator: (value) => value == null || value.isEmpty
                      ? 'Please enter a title'
                      : null,
                ),
                const SizedBox(height: 16),

                // Content
                TextFormField(
                  controller: _contentController,
                  style: AppTextStyles.body,
                  maxLines: 3,
                  decoration: InputDecoration(
                    labelText: 'Content',
                    labelStyle: AppTextStyles.bodySecondary,
                    enabledBorder: const UnderlineInputBorder(
                      borderSide: BorderSide(color: AppColors.textSecondary),
                    ),
                    focusedBorder: const UnderlineInputBorder(
                      borderSide: BorderSide(color: AppColors.primaryPurple),
                    ),
                  ),
                  validator: (value) => value == null || value.isEmpty
                      ? 'Please enter content'
                      : null,
                ),
                const SizedBox(height: 20),

                // Urgency Dropdown
                DropdownButtonFormField<NoteUrgency>(
                  value: _urgency,
                  dropdownColor: AppColors.cardDarkAlt,
                  style: AppTextStyles.body,
                  decoration: InputDecoration(
                    labelText: 'Urgency',
                    labelStyle: AppTextStyles.bodySecondary,
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                      borderSide: const BorderSide(
                        color: AppColors.textSecondary,
                      ),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                      borderSide: const BorderSide(
                        color: AppColors.primaryPurple,
                      ),
                    ),
                  ),
                  items: NoteUrgency.values.map((u) {
                    return DropdownMenuItem(
                      value: u,
                      child: Row(
                        children: [
                          Icon(
                            u == NoteUrgency.urgent
                                ? Icons.error_outline
                                : u == NoteUrgency.important
                                ? Icons.warning_amber_rounded
                                : Icons.info_outline,
                            color: u == NoteUrgency.urgent
                                ? AppColors.error
                                : u == NoteUrgency.important
                                ? AppColors.warning
                                : AppColors.textSecondary,
                            size: 18,
                          ),
                          const SizedBox(width: 8),
                          Text(u.name.toUpperCase()),
                        ],
                      ),
                    );
                  }).toList(),
                  onChanged: (val) {
                    if (val != null) {
                      setState(() => _urgency = val);
                    }
                  },
                ),
                const SizedBox(height: 16),

                // Pin Switch
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text('Pin to top', style: AppTextStyles.body),
                    Switch(
                      value: _isPinned,
                      activeColor: AppColors.primaryPurple,
                      onChanged: (val) => setState(() => _isPinned = val),
                    ),
                  ],
                ),
                const SizedBox(height: 24),

                // Actions
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    TextButton(
                      onPressed: () => Navigator.of(context).pop(),
                      child: Text('Cancel', style: AppTextStyles.bodySecondary),
                    ),
                    const SizedBox(width: 8),
                    ElevatedButton(
                      onPressed: _save,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primaryPurple,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                      child: Text('Save', style: AppTextStyles.button),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
